Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node1|
    node1.vm.hostname = "node1"
    node1.vm.box = "ubuntu/bionic64"
    node1.vbguest.auto_update = false
    node1.vm.network "private_network", ip: "192.168.56.101"
    node1.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.inventory_path = "inventario"
      ansible.config_file = "ansible.cfg"
      ansible.compatibility_mode = "2.0"
      ansible.become = true
    end
  end

  config.vm.define "node2" do |node2|
    node2.vm.hostname = "node2"
    node2.vm.box = "ubuntu/bionic64"
    node2.vbguest.auto_update = false
    node2.vm.network "private_network", ip: "192.168.56.102"
    node2.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.config_file = "ansible.cfg"
      ansible.inventory_path = "inventario"
      ansible.compatibility_mode = "2.0"
      ansible.become = true
    end
  end
end
